config/routes.rb
Rails.application.routes.draw do
  resources :dependents
  resources :belongings
  
  root to: 'pages#home'

  devise_for :users, controllers: { sessions: "users/sessions" }

  devise_scope :user do
    get "active", to: "users/sessions#active"
    get "timeout", to: "users/sessions#timeout"
  end

  get 'billing', to: 'billing#show'

  # get '/wills/new', to: 'wills#new'
  resources :users, only: :show do

    resource :billing_account

    resource :will, except: :index do 
      
      get 'preview', to: 'wills#preview'
      

      resources :bequests, only: [], param: :index do
        member do
          delete '(:id)', to: 'bequests#destroy', as: ""
          post ':/' => "bequests#create"
        end
      end
      
      resources :build, controller: 'wills/build'
      resource :testator
      resources :delegates
      resources :dependents
      resources :assets
              
      # put 'release', to: 'wills#release'

      # get 'access', to: 'access_payment#show'
      # get 'access/success', to: 'access_payment#success'

      get 'prepay', to: 'prepay_payment#show'
      get 'prepay/success', to: 'prepay_payment#success'

      # resource :biometric, only: :show do
      # 
      #   get 'payment', to: 'biometric_payment#show'
      #   get 'payment/success', to: 'biometric_payment#success'

      # end
    end
  end

  get 'home', to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'security', to: 'pages#security'
  get 'privacy', to: 'pages#privacy'
  get 'privacy_policy', to: 'pages#privacy_policy'
  get 'pricing', to: 'pages#pricing'
  get 'help', to: 'pages#help'

  get '/404', to: 'errors#not_found', as: 'not_found'
  get '/500', to: 'errors#internal_server', as: 'internal_server'
  get '/422', to: 'errors#unprocessable', as: 'unprocessable'

end

app/models/dependent.rb
class Dependent < ApplicationRecord
  belongs_to :will, counter_cache: true

  def full_name
    "#{self.first_name} #{self.last_name}".to_s
  end

  def initials
    "#{self.first_name.first}#{self.last_name.first}".upcase
  end

end

app/controllers/dependents_controller.rb
class DependentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_will
  before_action :set_dependent, only: %i[ show edit update destroy ]
  layout "dashboard"

  # GET /dependents or /dependents.json
  def index
  end

  # GET /dependents/1 or /dependents/1.json
  def show
  end

  # GET /dependents/new
  def new
    @dependent = @dependents.build
  end

  # GET /dependents/1/edit
  def edit
  end

  # POST /dependents or /dependents.json
  def create
    @dependent = @dependents.build(dependent_params)

    respond_to do |format|
      if @dependent.save
        @size = @will.dependents.size
        format.turbo_stream
        format.html { redirect_to dependent_url(@dependent), notice: "Dependent was successfully created." }
        format.json { render :show, status: :created, location: @dependent }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace("new_delegate_form", partial: "form", locals: { delegate: @delegate }), status: :unprocessable_entity }
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dependent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dependents/1 or /dependents/1.json
  def update
    respond_to do |format|
      if @dependent.update(dependent_params)
        format.turbo_stream
        format.html { redirect_to dependent_url(@dependent), notice: "Dependent was successfully updated." }
        format.json { render :show, status: :ok, location: @dependent }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace("delegate_#{@delegate.id}_form", partial: "form", locals: { delegate: @delegate }), status: :unprocessable_entity }
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dependent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dependents/1 or /dependents/1.json
  def destroy
    @dependent.destroy
    @size = @will.dependents.size

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to dependents_url, notice: "Dependent was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_will
      @will = current_user.will
      redirect_to :root if @will.nil?
      @dependents = @will.dependents
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_dependent
      @dependent = @dependents.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dependent_params
      params.require(:dependent).permit(
        :first_name, :last_name, :id, :_destroy
      )
    end
end

app/helpers/dependents_helper.rb
module DependentsHelper
end

app/views/dependents/_dependent.html.erb
<%= turbo_frame_tag "#{dom_id(dependent)}_item" do %>
<div class="relative rounded-lg border border-gray-300 bg-white px-6 py-5 shadow-sm flex items-center space-x-3">
  <div class="flex-1 min-w-0">
    <p class="text-sm font-medium text-gray-900"><%= dependent.full_name %></p>
    <p class="text-sm text-gray-500 truncate">Dependent</p>
  </div>
  <div class="relative z-0 inline-flex shadow-sm rounded-md">
    <%= link_to "Edit", edit_user_will_dependent_path(current_user, dependent), data: { turbo_frame: "model" }, class: "relative inline-flex items-center px-4 py-2 rounded-l-md border border-gray-300 bg-white text-sm font-medium text-gray-700 hover:bg-gray-50 focus:z-10 focus:outline-none focus:ring-1 focus:ring-indigo-500 focus:border-indigo-500"%>
    <%= button_to "Delete", user_will_dependent_path(current_user, dependent), form: { data: { turbo_confirm: "Are you sure?", turbo_frame: "_top" }}, method: :delete, class: "-ml-px relative inline-flex items-center px-3 py-2 rounded-r-md border border-gray-300 bg-white text-sm font-medium text-gray-700 hover:bg-gray-50 focus:z-10 focus:outline-none focus:ring-1 focus:ring-indigo-500 focus:border-indigo-500" %>
  </div>
</div>
<% end %>

app/views/dependents/_form.html.erb
<%= form_with model: [:user, :will, dependent], id: "#{dom_id(dependent)}_form", data: { turbo_frame: "_top"}, class: "sm:flex mt-5 sm:items-center" do |f| %>
<div class="relative z-10" aria-labelledby="modal-title" role="dialog" aria-modal="true">
  <div class="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity"></div>
  <div class="fixed z-10 inset-0 overflow-y-auto">
    <div class="sm:flex items-end sm:items-center justify-center min-h-full p-4 text-center sm:p-0">
      <div
        class="relative bg-white rounded-lg px-4 pt-3 pb-3 text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:max-w-lg sm:w-full sm:p-6">
        <div class="px-4 py-3 bg-white sm:p-6">

          <div class="grid grid-cols-6 gap-6">

            <div class="col-span-6">
              <%= render "shared/error_messages", resource: dependent %>
            </div>
            
            <div class="col-span-6">
              <div class="px-0 sm:px-0">
                <h3 class="text-lg font-medium leading-6 text-gray-900">Dependent Information</h3>
                <p class="mt-1 text-sm text-gray-600">This information will help identify the dependent on your will.
                  Please use their legal name.</p>
              </div>
            </div>

            <div class="col-span-6 sm:col-span-3">
              <%= f.label :first_name, class: "block text-sm font-medium text-gray-700" %>
              <%= f.text_field :first_name, autocomplete: "given-name", class: "mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md"%>
            </div>

            <div class="col-span-6 sm:col-span-3">
              <%= f.label :last_name, class: "block text-sm font-medium text-gray-700" %>
              <%= f.text_field :last_name, autocomplete: "family-name", class: "mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md"%>
            </div>

          </div>
          <div class="px-0 py-4 text-right justify-end">
            <%= link_to "Cancel", user_will_dependents_path(current_user), class: "bg-white py-2 px-4 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"%>
            <%= f.submit value: "Save", min: 0, max: 2, class: "inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"%>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% end %>

app/views/dependents/create.turbo_stream.erb
<% if @size == 1 %>
  <%= turbo_stream.replace "dependents_section" do %>
    <%= turbo_frame_tag "dependents_section", src: user_will_dependents_path(current_user) %>
  <% end %>
<% else %>
  <%= turbo_stream.append "dependents" do %>
    <%= render "dependent", dependent: @dependent %>
  <% end %>
  <% @dependents.each do |dependent| %>
    <% if dependent.saved_changes %>
      <%= turbo_stream.update "#{dom_id(dependent)}_item" do %>
        <%= render "dependent", dependent: dependent %>
      <% end %>
    <% end %>
  <% end %>
<% end %>
<%= turbo_stream.remove "#{dom_id(Dependent.new)}_form" %>

app/views/dependents/destroy.turbo_stream.erb
<%= turbo_stream.remove "#{dom_id(@dependent)}_item" %>
<% if @size == 0 %>
  <%= turbo_stream.replace "dependents_section" do %>
    <%= turbo_frame_tag "dependents_section", src: user_will_dependents_path(current_user) %>
  <% end %>
<% end %>

<% @dependents.each do |dependent| %>
  <% if dependent.saved_changes %>
    <%= turbo_stream.update "#{dom_id(dependent)}_item" do %>
      <%= render "dependent", dependent: dependent %>
    <% end %>
  <% end %>
<% end %>

app/views/dependents/edit.html.erb
<%= turbo_frame_tag "model" do %>
  <%= render "form", dependent: @dependent %>
<% end %>

app/views/dependents/index.html.erb
<%= turbo_frame_tag "dependents_section" do %>
  <% if @dependents.size == 0 %>
    <div class="bg-white shadow overflow-hidden rounded-lg">
      <div class="max-w-7xl mx-auto py-16 px-4 sm:py-24 sm:px-6 lg:px-8">
        <!-- This example requires Tailwind CSS v2.0+ -->
        <div class="text-center mx-auto max-w-lg">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="mx-auto h-12 w-12 text-gray-400" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 6a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0zM4.501 20.118a7.5 7.5 0 0114.998 0A17.933 17.933 0 0112 21.75c-2.676 0-5.216-.584-7.499-1.632z" />
          </svg>
          <h3 class="mt-2 text-sm font-medium text-gray-900">No Dependents</h3>
          <p class="mt-1 text-sm text-gray-500">Dependents are your children that are under the age of 18. Skip this section if you do not have any children.</p>
          <div class="mt-6">
            <%= link_to(new_user_will_dependent_path, data: { turbo_frame: "model" }, class: "inline-flex items-center px-4 py-2 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500") do %>
            <!-- Heroicon name: solid/plus -->
            <svg class="-ml-1 mr-2 h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor"
              aria-hidden="true">
              <path fill-rule="evenodd"
                d="M10 3a1 1 0 011 1v5h5a1 1 0 110 2h-5v5a1 1 0 11-2 0v-5H4a1 1 0 110-2h5V4a1 1 0 011-1z"
                clip-rule="evenodd" />
            </svg>
            Add Dependent
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% else %>
    <div class="flex items-center">
      <div class="flex-auto">
        <h1 class="text-xl font-semibold text-gray-900">Dependents</h1>
        <p class="mt-2 text-sm text-gray-700">Dependents are your children that are under the age of 18.</p>
      </div>
      <div class="mt-4 sm:mt-0 sm:ml-16 flex-none">
        <%= link_to(new_user_will_dependent_path, data: { turbo_frame: "model" }, class: "inline-flex items-center px-4 py-2 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500") do %>
        <!-- Heroicon name: solid/plus -->
        <svg class="-ml-1 mr-2 h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor"
          aria-hidden="true">
          <path fill-rule="evenodd"
            d="M10 3a1 1 0 011 1v5h5a1 1 0 110 2h-5v5a1 1 0 11-2 0v-5H4a1 1 0 110-2h5V4a1 1 0 011-1z"
            clip-rule="evenodd" />
        </svg>
        Add Dependent
        <% end %>
      </div>
    </div>
    <div id="dependents" class="relative mt-5 grid grid-cols-1 gap-4 sm:grid-cols-2">
      <%= render partial: "dependents/dependent", collection: @dependents %>
    </div>
  <% end %>
<% end %>

app/views/dependents/new.html.erb
<%= turbo_frame_tag "model" do %>
<%= render "form", dependent: @dependent, will: @will %>
<% end %>

app/views/dependents/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @dependent %>

<div>
  <%= link_to "Edit this dependent", edit_dependent_path(@dependent) %> |
  <%= link_to "Back to dependents", dependents_path %>

  <%= button_to "Destroy this dependent", @dependent, method: :delete %>
</div>

app/views/dependents/update.turbo_stream.erb
<% @dependents.each do |dependent| %>
  <% if dependent.saved_changes %>
    <%= turbo_stream.update "#{dom_id(dependent)}_item" do %>
      <%= render "dependent", dependent: dependent %>
    <% end %>
  <% end %>
<% end %>
<%= turbo_stream.remove "#{dom_id(@dependent)}_form" %>
<% @update_assets.each do |asset| %>
  <%= turbo_stream.update "#{dom_id(asset)}_item" do %>
    <%= render "assets/asset", asset: asset %>
  <% end %>
<% end %>