config/routes.rb
Rails.application.routes.draw do
  resources :dependents
  resources :belongings
  
  root to: 'pages#home'

  devise_for :users, controllers: { sessions: "users/sessions" }

  devise_scope :user do
    get "active", to: "users/sessions#active"
    get "timeout", to: "users/sessions#timeout"
  end

  get 'billing', to: 'billing#show'

  # get '/wills/new', to: 'wills#new'
  resources :users, only: :show do

    resource :billing_account

    resource :will, except: :index do 
      
      get 'preview', to: 'wills#preview'
      

      resources :bequests, only: [], param: :index do
        member do
          delete '(:id)', to: 'bequests#destroy', as: ""
          post ':/' => "bequests#create"
        end
      end
      
      resources :build, controller: 'wills/build'
      resource :testator
      resources :delegates
      resources :dependents
      resources :assets
              
      # put 'release', to: 'wills#release'

      # get 'access', to: 'access_payment#show'
      # get 'access/success', to: 'access_payment#success'

      get 'prepay', to: 'prepay_payment#show'
      get 'prepay/success', to: 'prepay_payment#success'

      # resource :biometric, only: :show do
      # 
      #   get 'payment', to: 'biometric_payment#show'
      #   get 'payment/success', to: 'biometric_payment#success'

      # end
    end
  end

  get 'home', to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'security', to: 'pages#security'
  get 'privacy', to: 'pages#privacy'
  get 'privacy_policy', to: 'pages#privacy_policy'
  get 'pricing', to: 'pages#pricing'
  get 'help', to: 'pages#help'

  get '/404', to: 'errors#not_found', as: 'not_found'
  get '/500', to: 'errors#internal_server', as: 'internal_server'
  get '/422', to: 'errors#unprocessable', as: 'unprocessable'

end

app/models/bequest.rb
class Bequest < ApplicationRecord
  belongs_to :asset
  belongs_to :beneficiariable, polymorphic: true
  validates :asset, :beneficiariable, presence: true
end

app/controllers/bequests_controller.rb
class BequestsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_will
  before_action :set_bequest, only: %i[ show edit update destroy ]

  # GET /bequests or /bequests.json
  def index
    @bequests = @will.bequests
  end

  # GET /bequests/1 or /bequests/1.json
  def show
  end

  # GET /bequests/new
  def new
    @bequest = @will.bequests.build
  end

  # GET /bequests/1/edit
  def edit
  end

  # POST /bequests or /bequests.json
  def create
    @bequest = @will.bequests.build(bequest_params)

    respond_to do |format|
      if @bequest.save
        format.html { redirect_to bequest_url(@bequest), notice: "Bequest was successfully created." }
        format.json { render :show, status: :created, location: @bequest }
        format.turbo_stream { render :show, status: :created, location: @bequest }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bequest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bequests/1 or /bequests/1.json
  def update
    respond_to do |format|
      if @bequest.update(bequest_params)
        format.html { redirect_to bequest_url(@bequest), notice: "Bequest was successfully updated." }
        format.json { render :show, status: :ok, location: @bequest }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bequest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bequests/1 or /bequests/1.json
  def destroy
    @bequest.destroy

    respond_to do |format|
      format.html { redirect_to bequests_url, notice: "Bequest was successfully destroyed." }
      format.json { head :no_content }
      format.turbo_stream { render :destroy, status: :ok, location: @bequest }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_will
      @will = current_user.will
      @will ? true : false
    end

    def set_bequest
      @bequest = current_user.bequests.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bequest_params
      params.require(:bequest).permit(:id, :_destroy, :will_id, :beneficiary_id, :percentage)
    end
end

app/helpers/bequests_helper.rb
module BequestsHelper
end

app/views/bequests/_bequest.html.erb
<div id="<%= dom_id bequest %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">New:</strong>
    <%= bequest.new %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Edit:</strong>
    <%= bequest.edit %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Create:</strong>
    <%= bequest.create %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Update:</strong>
    <%= bequest.update %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Destroy:</strong>
    <%= bequest.destroy %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this bequest", bequest, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this bequest', edit_bequest_path(bequest), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/bequests/_form.html.erb
<%# Takes in f: form, delegates: delegates %>
<div class="nested-fields col-span-1 relative">

    <%= f.hidden_field :beneficiariable_type, value: "Delegate" %>
    <%= f.hidden_field :_destroy, value: 0 %>

    <div class="grid grid-cols-3 gap-1 truncate mx-auto">
      <div class="col-span-2 flex items-center ">
        <%= f.label :beneficiariable_id, value: "Beneficiary", class: "hidden" %>
        <%= f.select :beneficiariable_id, delegates.collect{ |delegate| [ delegate.full_name, delegate.id ] }, {}, class: "inline-flex focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" %>
      </div>
      <div class="col-span-1 flex items-center ">
        <%= link_to "Remove", "#", data: { action: "click->nested-form#remove_association" },  class: "w-full inline-flex justify-center rounded-md border border-gray-300 shadow-sm px-4 py-2 bg-white text-base font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:mt-0 sm:col-start-1 sm:text-sm" %>
      </div>
    </div>
</div>

app/views/bequests/create.turbo_stream.html.erb
<%= turbo_stream.append "bequests", @bequest %>

<%= turbo_stream.replace "new_bequest" do %>
  <%= render partial: "new_bequest", locals: { } %>
<% end %>

app/views/bequests/destroy.turbo_stream.html.erb
<%= turbo_stream.remove "#{dom_id(@delegate)}_item" %>

app/views/bequests/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing bequest</h1>

  <%= render "form", bequest: @bequest %>

  <%= link_to "Show this bequest", @bequest, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to bequests", bequests_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/bequests/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Bequests</h1>
    <%= link_to 'New bequest', new_bequest_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="bequests" class="min-w-full">
    <%= render @bequests %>
  </div>
</div>

app/views/bequests/new.html.erb
<%= render "form", bequest: @bequest %>

app/views/bequests/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @bequest %>

    <%= link_to 'Edit this bequest', edit_bequest_path(@bequest), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this bequest', bequest_path(@bequest), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to bequests', bequests_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>