config/routes.rb
Rails.application.routes.draw do
  resources :dependents
  resources :belongings
  
  root to: 'pages#home'

  devise_for :users, controllers: { sessions: "users/sessions" }

  devise_scope :user do
    get "active", to: "users/sessions#active"
    get "timeout", to: "users/sessions#timeout"
  end

  get 'billing', to: 'billing#show'

  # get '/wills/new', to: 'wills#new'
  resources :users, only: :show do

    resource :billing_account

    resource :will, except: :index do 
      
      get 'preview', to: 'wills#preview'
      

      resources :bequests, only: [], param: :index do
        member do
          delete '(:id)', to: 'bequests#destroy', as: ""
          post ':/' => "bequests#create"
        end
      end
      
      resources :build, controller: 'wills/build'
      resource :testator
      resources :delegates
      resources :dependents
      resources :assets
              
      # put 'release', to: 'wills#release'

      # get 'access', to: 'access_payment#show'
      # get 'access/success', to: 'access_payment#success'

      get 'prepay', to: 'prepay_payment#show'
      get 'prepay/success', to: 'prepay_payment#success'

      # resource :biometric, only: :show do
      # 
      #   get 'payment', to: 'biometric_payment#show'
      #   get 'payment/success', to: 'biometric_payment#success'

      # end
    end
  end

  get 'home', to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'security', to: 'pages#security'
  get 'privacy', to: 'pages#privacy'
  get 'privacy_policy', to: 'pages#privacy_policy'
  get 'pricing', to: 'pages#pricing'
  get 'help', to: 'pages#help'

  get '/404', to: 'errors#not_found', as: 'not_found'
  get '/500', to: 'errors#internal_server', as: 'internal_server'
  get '/422', to: 'errors#unprocessable', as: 'unprocessable'

end

app/models/asset.rb
class Asset < ApplicationRecord
  include Collocable
  belongs_to :will, counter_cache: true
  has_many :bequests, dependent: :destroy
  accepts_nested_attributes_for :bequests, allow_destroy: true, reject_if: :all_blank
  has_many :beneficiaries, through: :bequests, source: :beneficiariable, source_type: "Delegate"
  
  validates :bequests, :title, presence: true
  validates :title, length: { in: 3..20 }
  after_initialize :bequests_valid?, unless: :new_record?

  def bequests_valid?
    if self.bequests.empty?
      self.errors.add(:beneficiaries, "can't be blank")
    end
    self.errors.empty?
  end

end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_will
  before_action :set_asset, only: %i[ show edit update destroy ]
  layout "dashboard"

  # GET /assets or /assets.json
  def index
    @assets = @will.assets.preload(:beneficiaries).preload(:address)
  end

  # GET /assets/1 or /assets/1.json
  def show
  end

  # GET /assets/new
  def new
    @asset = @will.assets.build
    @delegates = @will.delegates
  end

  # GET /assets/1/edit
  def edit
    @delegates = @will.delegates
  end

  # POST /assets or /assets.json
  def create
    @asset = @will.assets.build(asset_params)

    respond_to do |format|
      if @asset.save
        @size = @will.assets.size
        format.turbo_stream
        format.html { redirect_to user_will_assets_path(current_user), notice: "asset was successfully created." }
        format.json { render :show, status: :created, location: @asset }
      else
        @delegates = @will.delegates
        format.turbo_stream { render turbo_stream: turbo_stream.replace("new_asset_form", partial: "form", locals: { asset: @asset }), status: :unprocessable_entity }
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assets/1 or /assets/1.json
  def update
    respond_to do |format|
      if @asset.update(asset_params)
        format.turbo_stream
        format.html { redirect_to user_will_assets_path(current_user), notice: "asset was successfully updated." }
        format.json { render :show, status: :ok, location: @asset }
      else
        @delegates = @will.delegates
        format.turbo_stream { render turbo_stream: turbo_stream.replace("asset_#{@asset.id}_form", partial: "form", locals: { asset: @asset }), status: :unprocessable_entity }
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assets/1 or /assets/1.json
  def destroy
    @asset.destroy
    @size = @will.assets.size

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to assets_url, notice: "asset was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_will
      @will = current_user.will
      redirect_to :root if @will.nil?
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_asset
      @asset = @will.assets.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def asset_params
      params.require(:asset).permit(
        :id, :title, :description,
        address_attributes: [ :id, :line_1, :line_2, :city, :zone, :postal_code, :country_code, :_destroy ],
        bequests_attributes: [ :beneficiariable_id, :beneficiariable_type, :id, :_destroy ]
      )
    end
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/views/assets/_asset.html.erb
<%= turbo_frame_tag "#{dom_id(asset)}_item" do %>
<li class="h-full w-full px-4 pt-5 pb-4 bg-white rounded-lg shadow-md text-left space-y-2 flex flex-col justify-between">
  <div class="w-full flex items-center justify-between space-x-6">
    <div class="flex-1 truncate">
    
      <% if asset.errors.any? %>
        <div class="mb-3">
          <%= render "shared/error_messages", resource: asset %>
        </div>  
      <% end %>

      <div class="flex items-center">
        <h3 class="text-lg leading-6 font-medium text-gray-900"><%= asset.title %></h3>
        <% unless asset.address.nil? %>
          <span class="ml-1 flex-shrink-0 inline-block text-gray-500 text-sm truncate"> | <%= asset.address.short_line_address %></span>
        <% end %>
      </div>

      <% unless asset.beneficiaries.empty? %>
      <div class="my-1">
        <h2 class="text-gray-500 text-sm font-medium">Beneficiaries:</h2>
        <ul role="list" class="mt-2 flex flex-wrap gap-2">
          <% asset.beneficiaries.each do |delegate| %>
            <%= render "shared/delegate_small", delegate: delegate, color: "bg-indigo-600" %>
          <% end %>
        </ul>
      </div>  
      <% end %>

    </div>
  </div>
  <div class="mt-3 sm:grid sm:grid-cols-2 sm:gap-3 sm:grid-flow-row-dense">
    <%= link_to "Edit", edit_user_will_asset_path(current_user, asset), data: { turbo_frame: "model" }, class: "w-full inline-flex justify-center rounded-md border border-transparent shadow-sm px-4 py-2 bg-indigo-600 text-base font-medium text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:col-start-2 sm:text-sm"%>
    <%= button_to "Delete", user_will_asset_path(current_user, asset), form: { data: { turbo_confirm: "Are you sure?", turbo_frame: "_top" }}, method: :delete, class: "mt-3 w-full inline-flex justify-center rounded-md border border-gray-300 shadow-sm px-4 py-2 bg-white text-base font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:mt-0 sm:col-start-1 sm:text-sm" %>
  </div>
</li>
<% end %>

app/views/assets/_form.html.erb
<%= form_with model: [:user, :will, asset], id: "#{dom_id(asset)}_form", data: { turbo_frame: "_top" }, class: "sm:flex mt-5 sm:items-center" do |f| %>
<div class="relative z-10" aria-labelledby="modal-title" role="dialog" aria-modal="true">
  <div class="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity"></div>
  <div class="fixed z-10 inset-0 overflow-y-auto">
    <div class="sm:flex items-end sm:items-center justify-center min-h-full p-4 text-center sm:p-0">
      <div
        class="relative sm:mx-3 bg-white rounded-lg px-4 pt-3 pb-3 text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:max-w-4xl sm:w-full sm:p-6">
        <div class="px-4 py-3 bg-white sm:p-6">

          <div class="grid grid-cols-6 gap-6">

            <div class="col-span-6">
              <%= render "shared/error_messages", resource: asset %>
            </div>

            <div class="col-span-6">
              <div class="px-0 sm:px-0">
                <h3 class="text-lg font-medium leading-6 text-gray-900">Asset Information</h3>
                <p class="mt-1 text-sm text-gray-600">Please describe the asset or belonging you wish to bequest.</p>
              </div>
            </div>

            <div class="col-span-6 sm:col-span-4">
              <%= f.label :title, class: "block text-sm font-medium text-gray-700" %>
              <%= f.text_field :title, class: "mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md"%>
            </div>

            <div class="col-span-6 sm:col-span-4">
              <%= f.label :description, class: "block text-sm font-medium text-gray-700" %>
              <p class="text-sm text-gray-600">Optional</p>
              <%= f.text_area :description, class: "mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md"%>
            </div>

            <div class="col-span-6">
              <div class="px-0 sm:px-0">
                <h3 class="text-lg font-medium leading-6 text-gray-900">Address:</h3>
                <p class="mt-1 text-sm text-gray-600">Please add a legal address if applicable. This helps your beneficiaries identify the asset.</p>
              </div>
            </div>
            <div class="address_form col-span-6" data-controller="address-form">

              <template data-address-form-target='template'>
                <%= f.fields_for :address, Address.new, child_index: 'TEMPLATE_RECORD' do |ff| %>
                  <%= render "addresses/form", f: ff %>
                <% end %>
              </template>

              <%= f.fields_for :address do |ff| %>
                <%= render "addresses/form", f: ff %>
              <% end %>

              <div class="add_item relative flex items-center" data-address-form-target="add_item">
                <%= link_to "Add Address", "#", data: { action: "address-form#add_association" }, class: "inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
              </div>

            </div>

            <div class="col-span-6">
              <div class="px-0 sm:px-0">
                <h3 class="text-lg font-medium leading-6 text-gray-900">Beneficiary Information</h3>
                <p class="mt-1 text-sm text-gray-600">Choose which beneficiaries will recieve this asset or belonging.</p>
              </div>
            </div>

            <div class="nested_form col-span-6 grid grid-cols-1 gap-6 sm:grid-cols-2 " data-controller="nested-form">

              <template data-nested-form-target='template'>
                <%= f.fields_for :bequests, Bequest.new, child_index: 'TEMPLATE_RECORD' do |ff| %>
                  <%= render "bequests/form", f: ff, delegates: @delegates %>
                <% end %>
              </template>

              <%= f.fields_for :bequests do |ff| %>
                <%= render "bequests/form", f: ff, delegates: @delegates %>
              <% end %>

              <div class="relative flex items-center" data-nested-form-target="add_item">
                <%= link_to "Add Beneficiary", "#", data: { action: "nested-form#add_association" }, class: "inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
              </div>

            </div>

          </div>
          <div class="px-0 py-4 text-right justify-end">
            <%= link_to "Cancel", user_will_assets_path(current_user), class: "bg-white py-2 px-4 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"%>
            <%= f.submit value: "Save", class: "inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"%>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% end %>

app/views/assets/_no_assets.html.erb
<%= turbo_frame_tag "asset_section" do %>
<div class="bg-white shadow overflow-hidden rounded-lg">
  <div class="max-w-7xl mx-auto py-16 px-4 sm:py-24 sm:px-6 lg:px-8">
    <!-- This example requires Tailwind CSS v2.0+ -->
    <div class="text-center mx-auto max-w-lg">
      <svg class="mx-auto h-12 w-12 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor"
        aria-hidden="true">
        <path vector-effect="non-scaling-stroke" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
          d="M9 13h6m-3-3v6m-9 1V7a2 2 0 012-2h6l2 2h6a2 2 0 012 2v8a2 2 0 01-2 2H5a2 2 0 01-2-2z" />
      </svg>
      <h3 class="mt-2 text-sm font-medium text-gray-900">No Assets</h3>
      <p class="mt-1 text-sm text-gray-500">Continue by adding your assets. You can decide which delegate will recieve which asset or how an asset will be split amoungst multiple delegates.</p>
      <div class="mt-6">
        <%= link_to(new_user_will_asset_path, data: { turbo_frame: "model" }, class: "inline-flex items-center px-4 py-2 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500") do %>
        <!-- Heroicon name: solid/plus -->
        <svg class="-ml-1 mr-2 h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor"
          aria-hidden="true">
          <path fill-rule="evenodd"
            d="M10 3a1 1 0 011 1v5h5a1 1 0 110 2h-5v5a1 1 0 11-2 0v-5H4a1 1 0 110-2h5V4a1 1 0 011-1z"
            clip-rule="evenodd" />
        </svg>
        Add Asset
        <% end %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/assets/create.turbo_stream.erb
<% if @size == 1 %>
  <%= turbo_stream.replace "assets_section" do %>
    <%= turbo_frame_tag "assets_section", src: user_will_assets_path(current_user) %>
  <% end %>
<% else %>
  <%= turbo_stream.append "assets" do %>
    <%= render "asset", asset: @asset %>
  <% end %>
<% end %>
<%= turbo_stream.remove "#{dom_id(Asset.new)}_form" %>

app/views/assets/destroy.turbo_stream.erb
<%= turbo_stream.remove "#{dom_id(@asset)}_item" %>
<% if @size == 0 %>
  <%= turbo_stream.replace "assets_section" do %>
    <%= turbo_frame_tag "assets_section", src: user_will_assets_path(current_user) %>
  <% end %>
<% end %>

app/views/assets/edit.html.erb
<%= turbo_frame_tag "model" do %>
  <%= render "form", asset: @asset %>
<% end %>

app/views/assets/index.html.erb
<%= turbo_frame_tag "assets_section" do %>
  <% if @assets.size == 0 %>
    <div class="bg-white shadow overflow-hidden rounded-lg">
      <div class="max-w-7xl mx-auto py-16 px-4 sm:py-24 sm:px-6 lg:px-8">
        <!-- This example requires Tailwind CSS v2.0+ -->
        <div class="text-center mx-auto max-w-lg">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="mx-auto h-12 w-12 text-gray-400" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M21 11.25v8.25a1.5 1.5 0 01-1.5 1.5H5.25a1.5 1.5 0 01-1.5-1.5v-8.25M12 4.875A2.625 2.625 0 109.375 7.5H12m0-2.625V7.5m0-2.625A2.625 2.625 0 1114.625 7.5H12m0 0V21m-8.625-9.75h18c.621 0 1.125-.504 1.125-1.125v-1.5c0-.621-.504-1.125-1.125-1.125h-18c-.621 0-1.125.504-1.125 1.125v1.5c0 .621.504 1.125 1.125 1.125z" />
          </svg>
          <h3 class="mt-2 text-sm font-medium text-gray-900">No Bequests</h3>
          <p class="mt-1 text-sm text-gray-500">Continue by adding any assets you would like to bequest to a delegate or many delegates.</p>
          <div class="mt-6">
            <%= link_to(new_user_will_asset_path, data: { turbo_frame: "model" }, class: "inline-flex items-center px-4 py-2 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500") do %>
            <!-- Heroicon name: solid/plus -->
            <svg class="-ml-1 mr-2 h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor"
              aria-hidden="true">
              <path fill-rule="evenodd"
                d="M10 3a1 1 0 011 1v5h5a1 1 0 110 2h-5v5a1 1 0 11-2 0v-5H4a1 1 0 110-2h5V4a1 1 0 011-1z"
                clip-rule="evenodd" />
            </svg>
            Add bequest
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% else %>
    <div class="items-center">
      <div class="flex justify-between">
        <h1 class="block text-xl self-center font-semibold text-gray-900">Bequests</h1>
          <%= link_to(new_user_will_asset_path, data: { turbo_frame: "model" }, class: "inline-flex items-center px-4 py-2 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500") do %>
          <!-- Heroicon name: solid/plus -->
          <svg class="-ml-1 mr-2 h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor"
            aria-hidden="true">
            <path fill-rule="evenodd"
              d="M10 3a1 1 0 011 1v5h5a1 1 0 110 2h-5v5a1 1 0 11-2 0v-5H4a1 1 0 110-2h5V4a1 1 0 011-1z"
              clip-rule="evenodd" />
          </svg>
          Add bequest
          <% end %>
        </div>
      <p class="mt-3 text-sm max-w-2xl text-gray-700">Your bequests can include anything from property and finance to individual items. If you do not list a specific bequest, then it will be distributed equally among the delegates you choose to inherit your estate.</p>
    </div>
    <ul id="assets" role="list" class="relative mt-5 grid grid-cols-1 sm:grid-cols-2 gap-6 sm:auto-rows-fr">
      <%= render partial: "assets/asset", collection: @assets %>
    </ul>
  <% end %>
<% end %>

app/views/assets/new.html.erb
<%= turbo_frame_tag "model" do %>
  <%= render "form", asset: @asset, will: @will %>
<% end %>

app/views/assets/show.html.erb
<h1 class="text-lg">Should not be here</h1>
<%= render @asset %>

app/views/assets/update.turbo_stream.erb
<%= turbo_stream.update "#{dom_id(@asset)}_item" do %>
  <%= render "asset", asset: @asset %>
<% end %>
<%= turbo_stream.remove "#{dom_id(@asset)}_form" %>