config/routes.rb
Rails.application.routes.draw do
  resources :dependents
  resources :belongings
  
  root to: 'pages#home'

  devise_for :users, controllers: { sessions: "users/sessions" }

  devise_scope :user do
    get "active", to: "users/sessions#active"
    get "timeout", to: "users/sessions#timeout"
  end

  get 'billing', to: 'billing#show'

  # get '/wills/new', to: 'wills#new'
  resources :users, only: :show do

    resource :billing_account

    resource :will, except: :index do 
      
      get 'preview', to: 'wills#preview'
      

      resources :bequests, only: [], param: :index do
        member do
          delete '(:id)', to: 'bequests#destroy', as: ""
          post ':/' => "bequests#create"
        end
      end
      
      resources :build, controller: 'wills/build'
      resource :testator
      resources :delegates
      resources :dependents
      resources :assets
              
      # put 'release', to: 'wills#release'

      # get 'access', to: 'access_payment#show'
      # get 'access/success', to: 'access_payment#success'

      get 'prepay', to: 'prepay_payment#show'
      get 'prepay/success', to: 'prepay_payment#success'

      # resource :biometric, only: :show do
      # 
      #   get 'payment', to: 'biometric_payment#show'
      #   get 'payment/success', to: 'biometric_payment#success'

      # end
    end
  end

  get 'home', to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'security', to: 'pages#security'
  get 'privacy', to: 'pages#privacy'
  get 'privacy_policy', to: 'pages#privacy_policy'
  get 'pricing', to: 'pages#pricing'
  get 'help', to: 'pages#help'

  get '/404', to: 'errors#not_found', as: 'not_found'
  get '/500', to: 'errors#internal_server', as: 'internal_server'
  get '/422', to: 'errors#unprocessable', as: 'unprocessable'

end

app/controllers/biometric_payment_controller.rb
class BiometricPaymentController < ApplicationController
  before_action :authenticate_user!
  
  def show
    current_user.set_payment_processor :stripe
    current_user.payment_processor.customer 

    @checkout_session = current_user
      .payment_processor
      .checkout(
        mode: 'payment',
        line_items: 'price_1LViZKA4TChht1jzuFctq5e1',
        success_url: biometic_payment_success_user_will_url
      )
  end

  def success
  end

  def cancel

end

app/helpers/biometric_payment_helper.rb
module BiometricPaymentHelper
end

app/views/biometric_payment/cancel.html.erb
<h1>Payment canceled</h1>

app/views/biometric_payment/show.html.erb
<h1>Biometric payment</h1>
<p>Unfourtunately, Biometric authentication isn't cheap. We fronted the cost when you first created your will. However, if you wish to update your will, then you will have to pay the biometic authentication fee. It is only 3$.</p>

<%= render partial: 'pay/stripe/checkout_button', locals: {
  session: @checkout_session,
  title: "Pay biometric authentication fee"
} %>
<br/>
<%= link_to "No thanks", user_will_path(current_user) %>

app/views/biometric_payment/success.html.erb
<h1>Success!</h1>
<h2>Your total was: $<%= @session.total_amount.to_f / 100 %>
<br/>
<p>Please proceed to biometic authentication</p>